name: PDF Monitor

on:
  
    
  workflow_dispatch: {}   # allows manual run from the Actions tab

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed so we can commit the state file

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests beautifulsoup4
          fi

      - name: Run monitor script
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
          STATE_PATH: state/last_pdf_links.json
        run: python pdf_monitor.py

      - name: Commit state if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Update state [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
