name: PDF Monitor

on:
  schedule:
    # GitHub runs on UTC. Your timezone is Europe/London.
    # Summer (BST, UTC+1): 07:30–16:00 → 06:30–15:00 UTC
    - cron: "*/5 6-15 * * 1-5"
    # Winter (GMT, UTC+0): 07:30–16:00 → 07:30–16:00 UTC
    - cron: "*/5 7-16 * * 1-5"
  workflow_dispatch:  # allow manual run

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests beautifulsoup4; fi

      - name: Run monitor script
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_APP_TOKEN: ${{ secrets.PUSHOVER_APP_TOKEN }}
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
        run: python pdf_monitor.py
